# Generated by Django 3.2.7 on 2021-09-29 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_record',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog_record',
            name='url',
        ),
        migrations.AddField(
            model_name='blog_record',
            name='data',
            field=models.DateField(default=datetime.date(2021, 9, 29)),
        ),
        migrations.AlterField(
            model_name='blog_record',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog_record',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
